name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: 📦 Generate build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        run: pnpm run lint

      - name: Validation of types
        run: pnpm run ts:check

      - name: Validation of types
        run: pnpm run test:ci

      - name: Generate build
        run: pnpm run build